In [9]:
import pandas as pd 
import matplotlib.pyplot as plt 

df = pd.read_csv("C:\\Users\\nmsmi\\DataScienceGuidedCapstone\\ObesityDataSet_raw_and_data_sinthetic.csv")
df.head()

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad
0,21.0,Female,1.62,64.0,no,no,2.0,3.0,no,no,2.0,yes,0.0,1.0,Sometimes,Public_Transportation,Normal_Weight
1,21.0,Female,1.52,56.0,Sometimes,no,3.0,3.0,yes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,23.0,Male,1.80,77.0,Frequently,no,2.0,3.0,no,no,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Normal_Weight
3,27.0,Male,1.80,87.0,Frequently,no,3.0,3.0,no,no,2.0,no,2.0,0.0,Sometimes,Walking,Overweight_Level_I
4,22.0,Male,1.78,89.8,Sometimes,no,2.0,1.0,no,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [10]:
dummy = pd.get_dummies(df['Gender'])
dummy.head()

   Female   Male
0    True  False
1    True  False
2   False   True
3   False   True
4   False   True

In [11]:
dfo=df.select_dtypes(include=['object'])

In [12]:
df= pd.concat([df,dummy],axis=1)
df.head()

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad,Female,Male
0,21.0,Female,1.62,64.0,no,no,2.0,3.0,no,no,2.0,yes,0.0,1.0,Sometimes,Public_Transportation,Normal_Weight,True,False
1,21.0,Female,1.52,56.0,Sometimes,no,3.0,3.0,yes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,True,False
2,23.0,Male,1.80,77.0,Frequently,no,2.0,3.0,no,no,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Normal_Weight,False,True
3,27.0,Male,1.80,87.0,Frequently,no,3.0,3.0,no,no,2.0,no,2.0,0.0,Sometimes,Walking,Overweight_Level_I,False,True
4,22.0,Male,1.78,89.8,Sometimes,no,2.0,1.0,no,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,False,True

In [13]:
df = df.merge(dummy, left_index=True, right_index=True)
df.head()

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,...,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad,Female_x,Male_x,Female_y,Male_y
0,21.0,Female,1.62,64.0,no,no,2.0,3.0,no,no,...,yes,0.0,1.0,Sometimes,Public_Transportation,Normal_Weight,True,False,True,False
1,21.0,Female,1.52,56.0,Sometimes,no,3.0,3.0,yes,yes,...,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,True,False,True,False
2,23.0,Male,1.80,77.0,Frequently,no,2.0,3.0,no,no,...,yes,2.0,1.0,Sometimes,Public_Transportation,Normal_Weight,False,True,False,True
3,27.0,Male,1.80,87.0,Frequently,no,3.0,3.0,no,no,...,no,2.0,0.0,Sometimes,Walking,Overweight_Level_I,False,True,False,True
4,22.0,Male,1.78,89.8,Sometimes,no,2.0,1.0,no,no,...,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,False,True,False,True